name: AI Publisher

on:
  workflow_dispatch: {}
  schedule:
    # runs every 3 hours — adjust as you like
    - cron: "0 */3 * * *"

permissions:
  contents: write   # needed to push the new post file

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install openai google-api-python-client jsonschema

      - name: Run publisher
        env:
          # Built-in Actions token (has repo permissions because of permissions: contents: write)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # OpenAI
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-4.1
          # Optional (fresh source snippets). If you don't set these, the script may no-publish.
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          SEARCH_ENGINE_ID: ${{ secrets.SEARCH_ENGINE_ID }}
          # Optional overrides (defaults shown)
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO: ${{ github.event.repository.name }}
          POSTS_DIRECTORY: _posts
        run: |
          python publish_openai.py
