name: Daily AI-Powered Blog Post

on:
  # This schedule runs the job every day at 08:00 UTC (you can change the time)
  schedule:
    - cron: '0 8 * * *'
  # This line allows you to run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests google-generativeai google-api-python-client

      - name: Run the AI Publisher Script
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          SEARCH_ENGINE_ID: ${{ secrets.SEARCH_ENGINE_ID }}
        run: |
          python publish.py "the most important cybersecurity news or zero-day vulnerability disclosed in the last 24 hours"
