name: Autonomous AI Blog Publisher

on:
  # This schedule runs the job every 3 hours.
  schedule:
    - cron: '0 */3 * * *'
  # This line allows you to run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests google-generativeai google-api-python-client

      - name: Run the AI Publisher Script
        env:
          # **FIXED LINE:** Changed the environment variable name to match what the script expects.
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          SEARCH_ENGINE_ID: ${{ secrets.SEARCH_ENGINE_ID }}
        run: |
          python publish.py

